name: xpert_goup_tecnical_test
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  dio: ^5.1.2
  qr_flutter: ^4.0.0
  share_plus: ^7.0.0
  path_provider: ^2.0.11
  flutter_screenutil: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OpenSans_Bold
      fonts:
        - asset: fonts/OpenSans/OpenSans_Bold.ttf
          style: normal
    - family: OpenSans_BoldItalic
      fonts:
        - asset: fonts/OpenSans/OpenSans_BoldItalic.ttf
          style: normal
    - family: OpenSans_ExtraBold
      fonts:
        - asset: fonts/OpenSans/OpenSans_ExtraBold.ttf
          style: normal
    - family: OpenSans_ExtraBoldItalic
      fonts:
        - asset: fonts/OpenSans/OpenSans_ExtraBoldItalic.ttf
          style: normal
    - family: OpenSans_Italic
      fonts:
        - asset: fonts/OpenSans/OpenSans_Italic.ttf
          style: normal
    - family: OpenSans_Light
      fonts:
        - asset: fonts/OpenSans/OpenSans_Light.ttf
          style: normal
    - family: OpenSans_LightItalic
      fonts:
        - asset: fonts/OpenSans/OpenSans_LightItalic.ttf
          style: normal
    - family: OpenSans_Medium
      fonts:
        - asset: fonts/OpenSans/OpenSans_Medium.ttf
          style: normal
    - family: OpenSans_MediumItalic
      fonts:
        - asset: fonts/OpenSans/OpenSans_MediumItalic.ttf
          style: normal
    - family: OpenSans_Regular
      fonts:
        - asset: fonts/OpenSans/OpenSans_Regular.ttf
          style: normal
    - family: OpenSans_SemiBold
      fonts:
        - asset: fonts/OpenSans/OpenSans_SemiBold.ttf
          style: normal
    - family: OpenSans_SemiBoldItalic
      fonts:
        - asset: fonts/OpenSans/OpenSans_SemiBoldItalic.ttf
          style: normal
